import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/hero";
import AboutUs from "@/components/about-us";
import Features from "@/components/features";
import Works from "@/components/works";
import ContactUs from "@/components/contact-us";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ARKE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <AboutUs />
        <Features />
        <Works />
        <ContactUs />
      </main>
    </>
  );
}
